# Generated by Django 3.1.4 on 2020-12-15 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_auto_20201215_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название магазина')),
                ('url', models.URLField(verbose_name='Ссылка на магазин')),
                ('description', models.CharField(max_length=600, verbose_name='Описание магазина')),
                ('rating', models.FloatField(default='0', max_length=5, verbose_name='Рейтинг магазина')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('logo_link', models.URLField(verbose_name='Ссылка на логотип магазина')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='Ссылка на раздел магазина (категория)')),
                ('status', models.IntegerField(choices=[(1, 'Список товаров не получен'), (2, 'Список товаров получен')], default=1, verbose_name='Статус задания')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Категория')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.seller', verbose_name='Продавец')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название продукта')),
                ('url', models.URLField(unique=True, verbose_name='Ссылка на продукт')),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Обычная цена')),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Цена со скидкой')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Старая цена (без скидки)')),
                ('image_url', models.URLField(verbose_name='Ссылка на изображение товара')),
                ('publish_date', models.DateTimeField(verbose_name='Дата добавления')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Категория')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraping.seller', verbose_name='Продавец')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.subcategory', verbose_name='Подкатегория')),
                ('task', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='scraping.task')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
