# Generated by Django 3.1.4 on 2020-12-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='logo_link',
            field=models.ImageField(null=True, upload_to='', verbose_name='Логотип магазина'),
        ),
    ]
