# Generated by Django 3.1.4 on 2020-12-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_auto_20201215_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='logo_link',
        ),
        migrations.AddField(
            model_name='seller',
            name='logo',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Логотип магазина'),
        ),
    ]
